In [2]:
%matplotlib tkagg
#%matplotlib inline
#%matplotlib widget
#%matplotlib qt

Warning: Cannot change to a different GUI toolkit: tk. Using qt instead.

ImportError: Failed to import any of the following Qt binding modules: PyQt6, PySide6, PyQt5, PySide2

In [33]:
%pwd

'/Users/John/Dev/PythonScripts/DataGopher/srcnew'

In [3]:
run datagopher.py

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Users/John/miniconda3/envs/jptr/lib/python3.14/tkinter/__init__.py", line 2082, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "/Users/John/Dev/PythonScripts/DataGopher/srcnew/goModel.py", line 728, in modelplot
    fig = plt.figure(figsize = (8,8))
  File "/Users/John/miniconda3/envs/jptr/lib/python3.14/site-packages/matplotlib/pyplot.py", line 1041, in figure
    manager = new_figure_manager(
        num, figsize=figsize, dpi=dpi,
        facecolor=facecolor, edgecolor=edgecolor, frameon=frameon,
        FigureClass=FigureClass, **kwargs)
  File "/Users/John/miniconda3/envs/jptr/lib/python3.14/site-packages/matplotlib/pyplot.py", line 550, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/John/miniconda3/envs/jptr/lib/python3.14/site-packages/matplotlib/pyplot.py", line 527, in _warn_if_gui_out_of_main_thread
    canvas_class = cast(type[FigureCanvasBase], _get_backend_mod().FigureCanvas)
                                                ~~~~~~~~~~~~~~~~^^
  File "/Users/John/miniconda3/envs/jptr/lib/python3.14/site-packages/matplotlib/pyplot.py", line 368, in _get_backend_mod
    switch_backend(rcParams._get("backend"))
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/John/miniconda3/envs/jptr/lib/python3.14/site-packages/matplotlib/pyplot.py", line 424, in switch_backend
    module = backend_registry.load_backend_module(newbackend)
  File "/Users/John/miniconda3/envs/jptr/lib/python3.14/site-packages/matplotlib/backends/registry.py", line 317, in load_backend_module
    return importlib.import_module(module_name)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/Users/John/miniconda3/envs/jptr/lib/python3.14/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1398, in _gcd_import
    return _find_and_load(name, _gcd_import)
  File "<frozen importlib._bootstrap>", line 1371, in _find_and_load
    return _find_and_load_unlocked(name, import_)
  File "<frozen importlib._bootstrap>", line 1342, in _find_and_load_unlocked
    module = _load_unlocked(spec)
  File "<frozen importlib._bootstrap>", line 938, in _load_unlocked
    spec.loader.exec_module(module)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 762, in exec_module
    _bootstrap._call_with_frames_removed(exec, code, module.__dict__)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 491, in _call_with_frames_removed
    return f(*args, **kwds)
  File "/Users/John/miniconda3/envs/jptr/lib/python3.14/site-packages/matplotlib/backends/backend_qtagg.py", line 9, in <module>
    from .qt_compat import QT_API, QtCore, QtGui
  File "/Users/John/miniconda3/envs/jptr/lib/python3.14/site-packages/matplotlib/backends/qt_compat.py", line 130, in <module>
    raise ImportError(
    ...<2 lines>...
    )
ImportError: Failed to import any of the following Qt binding modules: PyQt6, PySide6, PyQt5, PySide2

After quitting datagopher, internal data (input data, most recent model results, etc) are available in the "globals" dictionary.  Let's see what's inside of globals() by listing out the values of it's keys.

In [17]:
globals().keys()

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', '_1', '_i2', '_i3', '_i4', '_i5', '_5', '_i6', '_6', '_i7', '_7', '_i8', '_i9', '_9', '_i10', '__nonzero__', 'sys', 'pd', 'imdl', 'tk', 'filedialog', 'messagebox', 'scrolledtext', 'ttk', 'plt', 'np', 'godf', 'gopt', 'gosc', 'gopv', 'gdata', 'datetime', 're', 'checkName', 'goStat', 'app', '_i11', '_11', '_i12', '_i13', '_13', '_i14', '_14', '_i15', '_15', '_i16', 'myobj', 'mymodel', '_i17'])

That's messy, lets get rid of the "system" variables (the ones that start with an underscore)

In [18]:
#note flashy python code
", ".join([item for item in list(globals().keys()) if not item.startswith('_')])

'In, Out, get_ipython, exit, quit, open, sys, pd, imdl, tk, filedialog, messagebox, scrolledtext, ttk, plt, np, godf, gopt, gosc, gopv, gdata, datetime, re, checkName, goStat, app, myobj, mymodel'

 'gdata' is an instance of the class globalData() (in globalData.py) in which datagopher stores data shared among the various modules of DataGopher.  'imdl' is and instance of the class modelData() (in Regression.py) which contains the internal data for the most recent model fit.  globals()['gdata'] accesses a member of that object.  For example the current data set is in globals()['gdata'].data  the current model

In [6]:
globals()['gdata'].data.head(5)

,RowNumber,Original_Row,carat,cut,color,clarity,depth,table,price,x,y,z,carat_2,carat_3
0,0,90,0.70,Ideal,E,SI1,62.5,57.0,2757,5.70,5.72,3.57,0.4900,0.343000
1,1,91,0.86,Fair,E,SI2,55.1,69.0,2757,6.45,6.33,3.52,0.7396,0.636056
2,2,93,0.71,Very Good,E,VS2,62.4,57.0,2759,5.68,5.73,3.56,0.5041,0.357911
3,3,95,0.70,Good,E,VS2,57.5,58.0,2759,5.85,5.90,3.38,0.4900,0.343000
4,4,98,0.73,Very Good,E,SI1,61.6,59.0,2760,5.77,5.78,3.56,0.5329,0.389017

An easy thing to do is to fetch the gdata and imdl classes and rename them you can manipulate them more easily.

In [26]:
myobj = globals()['gdata']
mymodel = globals()['imdl']

In [28]:
print("_________________myobj (gdata)_______________________________________")
print(", ".join([item for item in  list(dir(myobj)) if not item.startswith('_')]))
print("=====================================================================")
print("_________________mymodel (imdl)______________________________________")
    
print(", ".join([item for item in  list(dir(mymodel)) if not item.startswith('_')]))
print("=====================================================================")

_________________myobj (gdata)_______________________________________
code_Get, code_Init, code_It, codestr, data, datatable, fpath, get_Data, log_Get, log_Init, log_It, logstr, model_data, model_res, put_Data, reset_Data, restore_Data, show_Data
=====================================================================
_________________mymodel (imdl)______________________________________
LOGSTR, addPredictions, clearlog, depvar, fitdata, fname, indvars, inputdata, link, modelData_Clear, model_string, model_type, model_vars, modelres, overdispersion, pushlog, sig_level
=====================================================================

In [29]:
print(myobj.codestr)

# 2026-04-30 10:07:25 Code:
df = pd.read_csv('/Users/John/Dev/PythonScripts/DataFiles/Diamonds.csv',engine='python')
################################
## Code for Histogram Plot

df = pd.read_csv('/Users/John/Dev/PythonScripts/DataFiles/Diamonds.csv',engine='python')
nobs0 = len(df)
df.dropna(subset=['carat'], inplace = True)
nobs = len(df)
fg=sb.displot(df, **{'x': 'carat', 'hue': None, 'row': None, 'col': None, 'kde': False, 'bins': 'auto', 'palette': None, 'facet_kws': {'margin_titles': True}})
fg.set_axis_labels('carat', 'Count')
fg.set(xlim=(0.2, 5.01))
plt.subplots_adjust(left=0.1, right=0.9, top=0.9, bottom=0.1)
plt.suptitle(t='(53940 rows out of 53940)', y=0.95)
plt.show()
#fg.figure.show()
depvar = 'price'
indvars = ['table', 'carat']
df.dropna(subset = ['price', 'table', 'carat'], inplace = True)
res = smf.ols(formula='price~carat+table + I(carat**2)', data = df).fit()
mdl_d = pd.concat([res.model.data.orig_exog,res.model.data.orig_endog],axis = 1).copy(deep = True)
print(res.summary(alpha = 0.05))
#### Model Graphics Options (comment or uncomment as needed)####
grp.modelplot(res, depvar = 'price', indvars = ['table', 'carat'],color_var = '-', showCI = False, showPI = False, MTYPE = 'OLS')
grp.modelplot(res, depvar = 'price', indvars = ['table', 'carat'],color_var = 'color', showCI = False, showPI = False, MTYPE = 'OLS')
grp.modelplot(res, depvar = 'price', indvars = ['table', 'carat'],color_var = 'color', showCI = False, showPI = False, MTYPE = 'OLS')

In [24]:
print(mymodel.modelres.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.852
Model:                            OLS   Adj. R-squared:                  0.852
Method:                 Least Squares   F-statistic:                 1.039e+05
Date:                Thu, 30 Apr 2026   Prob (F-statistic):               0.00
Time:                        13:39:07   Log-Likelihood:            -4.7217e+05
No. Observations:               53940   AIC:                         9.443e+05
Df Residuals:                   53936   BIC:                         9.444e+05
Df Model:                           3
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept      2107.2844    171.096     12.316      0.000    1771.936    2442.633
carat          6802.7454     46.491    146.324      0.000    6711.623    6893.868
table           -69.8513      3.009    -23.213      0.000     -75.749     -63.953
I(carat ** 2)   476.8967     20.760     22.972      0.000     436.208     517.586
==============================================================================
Omnibus:                    14006.304   Durbin-Watson:                   1.131
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           340017.815
Skew:                           0.694   Prob(JB):                         0.00
Kurtosis:                      15.221   Cond. No.                     1.49e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.49e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
There is some redundancy between gdata and imdl, for example the same report can be obtained from gdata (via myobj):

In [25]:
print(myobj.model_res.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.852
Model:                            OLS   Adj. R-squared:                  0.852
Method:                 Least Squares   F-statistic:                 1.039e+05
Date:                Thu, 30 Apr 2026   Prob (F-statistic):               0.00
Time:                        13:42:41   Log-Likelihood:            -4.7217e+05
No. Observations:               53940   AIC:                         9.443e+05
Df Residuals:                   53936   BIC:                         9.444e+05
Df Model:                           3
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept      2107.2844    171.096     12.316      0.000    1771.936    2442.633
carat          6802.7454     46.491    146.324      0.000    6711.623    6893.868
table           -69.8513      3.009    -23.213      0.000     -75.749     -63.953
I(carat ** 2)   476.8967     20.760     22.972      0.000     436.208     517.586
==============================================================================
Omnibus:                    14006.304   Durbin-Watson:                   1.131
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           340017.815
Skew:                           0.694   Prob(JB):                         0.00
Kurtosis:                      15.221   Cond. No.                     1.49e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.49e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

the object imdl offers a little more detail about the model fit inparticular fitdata contains the data used to fit the modeland the resulting residuals, confidence and prediction intervals.

In [31]:
mymodel.fitdata.head(5)

,Intercept,carat,table,I(carat ** 2),price,CI_lb,CI_ub,PI_lb,PI_ub,Predictions,Residuals,OBS,cut,color,clarity,depth,x,y,z
0,1.0,0.23,55.0,0.0529,326.0,-172.627403,-116.729946,-3148.483689,2859.126340,-144.678674,470.678674,1,Ideal,E,SI2,61.5,3.95,3.98,2.43
1,1.0,0.21,61.0,0.0441,326.0,-740.880494,-667.195845,-3707.939099,2299.862759,-704.038170,1030.038170,2,Premium,E,SI1,59.8,3.89,3.84,2.31
2,1.0,0.23,65.0,0.0529,327.0,-898.070442,-788.313224,-3847.368109,2160.984443,-843.191833,1170.191833,3,Good,E,VS1,56.9,4.05,4.07,2.31
3,1.0,0.29,58.0,0.0841,334.0,45.298169,92.324396,-2934.955736,3072.578301,68.811283,265.188717,4,Premium,I,VS2,62.4,4.20,4.23,2.63
4,1.0,0.31,58.0,0.0961,335.0,188.075826,233.102078,-2793.170405,3214.348310,210.588952,124.411048,5,Good,J,SI2,63.3,4.34,4.35,2.75

The easiest way to see the complete inventory of what you can get from gdata is to look at the class specification globalData.py.  Handily reproduced below:


self.data  #----> the input data
self.fpath  #----> path to the input data
self.model_res  #----> last model results
self.model_data  #----> copy of the data used to fit the last model
self.datatable #----> the last pivot table produced
self.logstr = ''       #----> the log (a long string)
self.codestr = ''       #----> code produced in this session (a long string)

In [19]:
globals().keys()

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', '_i2', '__nonzero__', 'sys', 'pd', 'imdl', 'tk', 'filedialog', 'messagebox', 'scrolledtext', 'ttk', 'plt', 'np', 'godf', 'gopt', 'gosc', 'gopv', 'gdata', 'datetime', 're', 'checkName', 'goStat', 'app', '_i3', '_3', '_i4', '_4', '_i5', 'myobj', '_i6', '_6', '_i7', '_i8', '_8', '_i9', '_9', '_i10', '_10', '_i11', '_i12', '_12', '_i13', '_i14', '_i15', '_15', '_i16', '_i17', '_i18', '_18', '_i19'])

In [22]:
globals()['imdl'].model_type

'OLS'

In [ ]:
As you can see seplunking through the data left by DataGopher can provide hours of fun for the entire family.